### ISSUE TITLE
Convert Contrib Folder To Repository List

### ISSUE THREAD

**Issue by aminhusni** [CITF-Malaysia/citf-public#11]
Suggestion:
Rather than committing the contribution codes directly into this repository, use a text list linking all contributor's project repositories instead. 

This would eliminate the need to constantly review pull requests and the liability of having 3rd party codes under CTIF's official repository. This also eliminates the need to introduce a pull request every time a 3rd party updates their code.

**Comment by CITF-Malaysia** [comment]
Good point - taken up [here](https://github.com/CITF-Malaysia/citf-public/blob/main/CONTRIB.md). Thank you!
