### ISSUE TITLE
negative value in vax_state.csv

### ISSUE THREAD

**Issue by gohkt** [CITF-Malaysia/citf-public#118]
2021-09-13, W.P. Putrajaya, daily_partial_child value is recorded as -2. Is that correct?

**Comment by gohkt** [comment]
It seems the -2 value also affected the vax_malaysia.csv for 2021-09-13 value for daily_partial_child. 

In vax_malaysia.csv on 2021-09-13, it is recorded as 6,162.

In vax_state.csv on 2021-09-13, sum of all states except Putrajaya is 6,164. 

6,164 + (-2) = 6,162 (vax_malaysia.csv)

**Comment by alexandereric995** [comment]
sorry for asking, but no such information as vax_state, the system only use [data-v-number] for graph.  Neither for the style.  May i know which link for CS do you refer to? or maybe on your excel?

**Comment by alexandereric995** [comment]
What i am stating above as my point of bad consequence is, you may do google search about covid19 surgery.

**Comment by gohkt** [comment]
Data pulled on 23rd Sept has updated the -2 value to 0 for 021-09-13, W.P. Putrajaya, daily_partial_child in vax_state.csv.
