### ISSUE TITLE
Vaccinations available versus shots in arms

### ISSUE THREAD

**Issue by byte** [CITF-Malaysia/citf-public#24]
We all know what the daily rate of vaccines being given is thanks to you sharing that data.

But let us see how effective you are, by also sharing the "burn down" of vaccine shots available versus shots given in arms. 

This corpus of data only needs to be updated when arrivals of vaccines come. Provide historical data too, to ensure that we really did ramp up effectively.

E.g. Today the USA donated some Pfizer vaccines. This should be in the file. We need to know what's donated, what's paid for, what arrived, when it arrived, and how quickly they're going into arms.

Main reason is if we are to achieve phase two or three, with a vaccine component thrown into the mix (silly, but this is what it is), this data is crucial to share.

Also, share projections. Can't always blame the EU or First world for holding vaccines back. If you ordered something and it was delayed, the data will tell us all, rather than the "Vaccine Tsar" just shooting his mouth off.

**Comment by CITF-Malaysia** [comment]
Fair request - could we ask that you submit a pull request [here](/CONTRIB.md#data-requests) so we have the wishlist collated? :)
