### ISSUE TITLE
District and Municipality Vaccination Data

### ISSUE THREAD

**Issue by ungkuamer** [CITF-Malaysia/citf-public#25]
Will a more specified (i.e districts, municipals) version of data for vaccine administration / vaccine registration be available? Will be useful to see which area have problems on vaccinations.

**Comment by psyntium** [comment]
As per [README.md](/README.md) @CITF-Malaysia would want you to submit a pull request [here](/CONTRIB.md#data-requests) so they can have the wishlist collated.
