### ISSUE TITLE
Latest on top

### ISSUE THREAD

**Issue by hariadi** [CITF-Malaysia/citf-public#29]
IMO, latest update (CSV) should put on top (ordered by latest date):

- No need to scroll to bottom and save time 😄 
- Easier to update?

**Comment by psyntium** [comment]
Following the standards as per https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data (assuming that this is the standard), time-series data is sorted in ascending order. Hence, the latest update should be at the bottom.

**Comment by CITF-Malaysia** [comment]
The data here is intended less for humans to scroll and view, and more to enable analysis/reporting for the entire community. The convention for time series data (which most analysts, data scientists and developers are used to) is data structured in ascending chronological order.
