### ISSUE TITLE
Please put more details as well

### ISSUE THREAD

**Issue by psyntium** [CITF-Malaysia/citf-public#3]
For example:
- Was a confirmed covid patient or not
- Type of vaccine
- age group
- gender
- malaysian/foreigner
- % vaccinated or % not vaccinated

**Comment by raziqraif** [comment]
It would be useful to have racial group as part of the demographic variables too.

And vaccine supply count (by location) and vaccine registration count (by demographics) to see what’s bottlenecking the distribution.

**Comment by yllvar** [comment]
In public health care, racial group data is unnecessary. Unless there is a specific race that immuned from the virus.

**Comment by raziqraif** [comment]
@yllvar I see. My comment was influenced by my observation of the CDC demographic variables (https://covid.cdc.gov/covid-data-tracker/#vaccination-demographic) but I appreciate the explanation, thanks!

**Comment by CITF-Malaysia** [comment]
We'll create a public file to consolidate wishlists. :)
