### ISSUE TITLE
population figures do not match JKJAV's

### ISSUE THREAD

**Issue by Ahmaz** [CITF-Malaysia/citf-public#36]
See https://www.vaksincovid.gov.my/en/statistics/

W.P. Kuala Lumpur @ 1,773,700 versus JKJAV's 1,610,305

**Comment by jozhuatwx** [comment]
If you're referring to the registration numbers, it uses the ≥18 population figure, which is 1,348,600. The website caps it at 100%. The vaccination rate uses the entire population, which is 1,773,700.

**Comment by psyntium** [comment]
as per @jozhuatwx mentioned, you can check the `TOTAL 1ST DOSE VACCINATIONS` under Kuala Lumpur is 1,369,537 at 77.21%. When you do the math, the population at 100% is about 1,773,782. which roughly matches the figure used.

**Comment by Ahmaz** [comment]
Hmm, I see. Maybe it would be best to note this in the respective readme.md?

**Comment by CITF-Malaysia** [comment]
All sources use the same population figures - however, we also see where you're coming from and will make a note if/where required!
