### ISSUE TITLE
Updates on data requests made via CONTRIB.md

### ISSUE THREAD

**Issue by joshuasthomas** [CITF-Malaysia/citf-public#43]
I'm aware that the section on Data Request is non-promissory but hopefully, there could be updates on whether each data request is either being reviewed, work in progress, or is rejected for a reason. Thanks.

**Comment by CITF-Malaysia** [comment]
Fair enough - we'll think of how best to indicate responses to the requests! Thanks for flagging.

**Comment by joshuasthomas** [comment]
Hi @CITF-Malaysia , I know that you had closed this issue, but I was wondering if you are going to proceed with my suggestion?
