### ISSUE TITLE
Different data with JKJAV Twitters

### ISSUE THREAD

**Issue by samleong123** [CITF-Malaysia/citf-public#47]
Different data on 15 July 2021 Total_Daily with JKJAV one 
On their Twitter they stated 460158 but on this repo Total_daily it was 460123

seems like the problem is on dose1_daily , JKJAV stated 304807 but on this repo it was 304772.

Is there any glitch on this data?

Source : https://twitter.com/JKJAVMY/status/1415833970118258690/photo/1
![Screenshot 2021-07-16 at 11 30 43](https://user-images.githubusercontent.com/58818070/125887439-5bf458ca-040a-4bfc-b3fc-68c163a94993.png)

**Comment by CITF-Malaysia** [comment]
Thanks for the eagle eye! This was due to a [backseries revision](https://github.com/CITF-Malaysia/citf-public/commit/2f3100bce891e34c660471ac4dc96dddb911e6eb#diff-61b43ea1f6043e3ce51f4264320ef8907ad059425fc3bcf7cc9f4c20fac3b025) which has been made public.
