### ISSUE TITLE
Request to have the data served with GitHub Pages

### ISSUE THREAD

**Issue by raziqraif** [CITF-Malaysia/citf-public#5]
I believe some developers would appreciate being able to make GET requests for the data from their website. Creating a project site for this repo with GitHub Pages can be a quick way to achieve that, and it only takes a couple of clicks from the repo's settings tab. 

After GitHub Pages is enabled, one can get the data by making a request to `https://citf-malaysia.github.io/citf-public/<path to file>`

Another thing that some may find nice to have is JSON-formatted data.

Note: 
The downside of serving the data with GitHub Pages is that we can't have robust APIs that can, for example, filter the data by date, etc. However, it is a quick way for us to have APIs for the data.

**Comment by leeliwei930** [comment]
Hi @raziqraif, I just create a pull request which contains a RESTAPI server that I wrote using Express JS which also support few queries based on state or local

#9

**Comment by pokgak** [comment]
Alternatively one can also fetch the data using the raw URL of the file e.g. for the Malaysia vax count: https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/vaccination/vax_malaysia.csv

A few project in the CONTRIB.md list uses this approach (mine included).
