### ISSUE TITLE
WPKL: Vaccinated > Registered

### ISSUE THREAD

**Issue by aidilsfwn** [CITF-Malaysia/citf-public#55]
As of 20-7-2021, the total number of registration in W.P. Kuala Lumpur is 1,801,763 but the total number of first dose administered is 1,835,737 (+33,974). Is this caused by walk-ins? Or is there any other explanation? Just curious.

**Comment by MoH-Malaysia** [comment]
As per [this issue](https://github.com/CITF-Malaysia/citf-public/issues/21).
