### ISSUE TITLE
Population that is vaccinated in other countries

### ISSUE THREAD

**Issue by AndrewChiaYJ** [CITF-Malaysia/citf-public#58]
Currently there are no data available for number of people who have taken their vaccination overseas, such as in Singapore, UK, Australia, etc. If this data is available, it will be a better gauge of the % of vaccinated population that is currently in Malaysia.

This data could be collected via voluntary submission of proof by citizens overseas.

**Comment by CITF-Malaysia** [comment]
We have a system in place to collect this already, and will consider publishing it when it is robust.
