### ISSUE TITLE
total_daily and cumul columns may not be needed

### ISSUE THREAD

**Issue by psyntium** [CITF-Malaysia/citf-public#6]
You can close this issue if you think otherwise.

but personally, for raw data, `total_daily`, `dose1_cumul`, `dose2_cumul`, and `total_cumul` may not be needed as those are calculated/generated from `dose1_daily` and `dose2_daily`.

If you're following specific standards, please mention it on the readme file for our reference.

**Comment by CITF-Malaysia** [comment]
You are correct that `dose1_daily` and `dose2_daily` are sufficient:

`total_daily` = `dose1_daily` + `dose2_daily`

`x_cumul` at time `T` = `sum x_daily` where `t <= T`

We provide it as a matter of convenience. Should we serve the data via Github pages (as raised in another issue), we would pare it down to the sufficient information!
