### ISSUE TITLE
Vaxreg_Malaysia Cumulative Figure Issue

### ISSUE THREAD

**Issue by hoe94** [CITF-Malaysia/citf-public#60]
Hi All,

Regarding to vaxreg_malaysia.csv, all the variables `x` value are cumulative data. 

But I realized that the cumulative data is decreasing between 19th July and 20th July for `call` and `web` variables.
![image](https://user-images.githubusercontent.com/17173021/126860140-c0e0d91d-08b1-412b-961c-f987bd6d6e25.png)

As we can see there's less 63 from 19th July to 20th July for `call` variable.

Appreciated that could resolve my concern about this.

Thanks a lot!

**Comment by CITF-Malaysia** [comment]
Good question, and eagle eyes - but no mistake.

If you review our procedure for de-duplication in the [documentation](https://github.com/CITF-Malaysia/citf-public/tree/main/registration#methodological-choices), you'll note the MySJ >> call >> web ordering.

Therefore, if a person who previously registered via the website creates a MySejahtera account, that looks like a +1 for `mysj` and a -1 for `web`. There is no change in the aggregate, but there is change in the composition.

**Comment by hoe94** [comment]
Hi Admin,

Thanks for clarify my concern. And kudos for you guys hard work on the data collection!
