### ISSUE TITLE
Total Population in Static Data (population.csv)

### ISSUE THREAD

**Issue by malcolmaaron22** [CITF-Malaysia/citf-public#69]
Does the first column (pop) indicate the total population for sum of adult (18+) and elderly (60+) population at the state level? If so, any reason why the differences between the sum and the value input in the pop column vary around 9-24% across the states? Might be something I missed out in my analysis. 
![Screenshot 2021-07-28 200632](https://user-images.githubusercontent.com/31904271/127319509-c02feaf8-2831-49b2-a737-d6d1b351885a.jpg)

**Comment by shenghann** [comment]
My understanding:
`pop_18` includes ages from 18 to 100+.
`pop_60` includes ages from 60 to 100+.
`pop` covers all ages.
Hence, `pop_60` is a subset of `pop_18`. Both are subsets of `pop`.

**Comment by CITF-Malaysia** [comment]
@shenghann is correct - `pop_60` is a subset of `pop_18` is a subset of `pop`.
