### ISSUE TITLE
Cumulative values doesn't tally with official announcement

### ISSUE THREAD

**Issue by uekichinos** [CITF-Malaysia/citf-public#70]
It seems like Cumulative values from csv doesn't tally with official announcement and this happen starting from 16 July onwards. Screenshot as below.

![WhatsApp Image 2021-07-30 at 10 33 21 AM](https://user-images.githubusercontent.com/1107546/127594278-5406acc1-fd2a-4dda-a6f1-6e8e7309b5f5.jpeg)

**Comment by joshuasthomas** [comment]
If I'm not mistaken, they did a manual revision of the vaccination doses on the 17th of July, which consolidates offline documentation of the vaccination program that was done days beforehand. It's mentioned in the [README.md](https://github.com/CITF-Malaysia/citf-public/blob/main/vaccination/README.md) for the vaccination data

**Comment by uekichinos** [comment]
yes, didnt see that. thank you
