### ISSUE TITLE
daily_partial is incorrect

### ISSUE THREAD

**Issue by hajime651118** [CITF-Malaysia/citf-public#81]
daily_partial should be
daily_partial = sinovac1 + pfyzer1 + astra1
Some are not same;

2021-08-06 W.P. Labuan
daily_partial = 177
sinovac1 = 9
pfyzer1 = 125
Astra = 0

2021-08-16 W.P. Putrajaya
daily_partial = 623
sinovac1 = 5
pfyzer1 = 594
astra1 = 0

**Comment by KennethThePro** [comment]
daily_partial would probably be correct for the date and state if the value in the pending column is 0.

If the value in the pending column for that date and state is not equal to 0, then it may be pending for either daily_partial or daily_full or both which results in the above differences.

**Comment by hajime651118** [comment]
I checked accumulated pending match with the difference.  It is 57,664 @2021-08-18
 
But I still don't know which one is actual vaccination dose.
